jobs:
  test:
    name: Run Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Tests
      run: bash ./gradlew build --stacktrace
name: RadioDroid CI
on:
  repository_dispatch:
    types: trigger-ga___android-ci.yml
