jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      id: avd-cache
      name: Restore Android virtual device
      uses: actions/cache@v3
      with:
        key: RadioDroid-${{ runner.os }}-avd-api${{ matrix.api-level }}
        path: '~/.android/avd/*

          ~/.android/adb*

          '
    - continue-on-error: true
      name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '11'
    - continue-on-error: true
      if: steps.avd-cache.outputs.cache-hit != 'true'
      name: Set up Android virtual device if not cached
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: ${{ matrix.api-level < 21 && 'x86' || 'x86_64' }}
        disable-animations: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          -camera-back none
        force-avd-creation: false
        script: echo "Generated AVD snapshot for caching."
        target: ${{ matrix.api-level >= 30 && 'google_apis' || 'default' }}
    - continue-on-error: true
      name: Run instrumented tests on Android virtual device
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: ${{ matrix.api-level < 21 && 'x86' || 'x86_64' }}
        disable-animations: true
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio
          -no-boot-anim -camera-back none
        force-avd-creation: false
        script: /Users/runner/Library/Android/sdk/platform-tools/adb uninstall net.programmierecke.radiodroid2.test;
          ./gradlew ${{ matrix.api-level < 26 && 'connectedFreeDebugAndroidTest' ||  matrix.api-level
          > 29 && 'installPlayDebugAndroidTest' || 'connectedCheck' }}
        target: ${{ matrix.api-level >= 30 && 'google_apis' || 'default' }}
    strategy:
      matrix:
        api-level:
        - 16
        - 27
        - 33
name: RadioDroid Instrumented Tests CI
on:
  repository_dispatch:
    types: trigger-ga___android-instrumented-tests-ci.yml
